version check of ImageMagick in configure script
git-svn-id: file:///home/git/hedgehog.fhcrc.org/bioconductor/trunk/madman/Rpacks/EBImage@26248 bc3139a8-67e5-0310-9ffc-ced21a209358

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1659,6 +1659,18 @@ fi
 
 if test "$magickfound" = "yes"; then
     echo ImageMagick version `Magick-config --version` found
+    ## check the version
+    Magick-config --version | head -n 1 | awk '{
+            gsub("\.", "", $1);
+            if ( substr($1,1,3) < 624 ) exit(1);
+            exit(0);
+          }'
+    ext=$?
+    if [ $ext -ge 1 ] ; then
+      { { echo "$as_me:$LINENO: error: \"ImageMagick version 6.2.4 required!\"" >&5
+echo "$as_me: error: \"ImageMagick version 6.2.4 required!\"" >&2;}
+   { (exit 1); exit 1; }; }
+    fi
     # Extract the first word of "Magick-config --cppflags", so it can be a program name with args.
 set dummy Magick-config --cppflags; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
