minor configure output modifications
git-svn-id: file:///home/git/hedgehog.fhcrc.org/bioconductor/trunk/madman/Rpacks/EBImage@26552 bc3139a8-67e5-0310-9ffc-ced21a209358

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1657,7 +1657,7 @@ fi
 
 
 if test "$magickfound" = "yes"; then
-    echo 'ImageMagick' version `Magick-config --version` found
+    echo "* found ImageMagick version `Magick-config --version`"
     ## check the version
     Magick-config --version | head -n 1 | awk '{
             x1 = substr($1,1,1);
@@ -1672,11 +1672,11 @@ if test "$magickfound" = "yes"; then
           }'
     ext=$?
     if [ $ext -ge 1 ] ; then
-      { { echo "$as_me:$LINENO: error: \"'ImageMagick' version >= 6.2.4 required\"" >&5
-echo "$as_me: error: \"'ImageMagick' version >= 6.2.4 required\"" >&2;}
+      { { echo "$as_me:$LINENO: error: \"Required ImageMagick version >= 6.2.4\"" >&5
+echo "$as_me: error: \"Required ImageMagick version >= 6.2.4\"" >&2;}
    { (exit 1); exit 1; }; }
     fi
-    echo 'ImageMagick' includes located in `Magick-config --cppflags`
+    echo "* found ImageMagick includes in `Magick-config --cppflags`"
     COMPILERFLAGS="`Magick-config --cflags`"
     COMPILERFLAGS="${COMPILERFLAGS} `Magick-config --cppflags`"
     CFLAGS="-Wall ${COMPILERFLAGS} ${CFLAGS}"
@@ -1686,8 +1686,8 @@ echo "$as_me: error: \"'ImageMagick' version >= 6.2.4 required\"" >&2;}
     LINKERFLAGS="${LINKERFLAGS} -lWand"
     LIBS="${LINKERFLAGS} ${LIBS} ${LFLAGS}"
 else
-    { { echo "$as_me:$LINENO: error: \"'ImageMagick' or 'ImageMagick' includes not found!\"" >&5
-echo "$as_me: error: \"'ImageMagick' or 'ImageMagick' includes not found!\"" >&2;}
+    { { echo "$as_me:$LINENO: error: \"ImageMagick or ImageMagick includes not found!\"" >&5
+echo "$as_me: error: \"ImageMagick or ImageMagick includes not found!\"" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -1774,7 +1774,7 @@ fi
 
 if test "$pkgfound" = "yes"; then
     if `$PKGCONF --cflags gtk+-2.0 > /dev/null` ; then
-        echo Compiling with GTK+ support
+        echo "* compiling with GTK+ support"
         COMPILERFLAGS="`$PKGCONF --cflags gtk+-2.0`"
         CFLAGS="-DUSE_GTK -DGLIB_GETTEXT ${COMPILERFLAGS} ${CFLAGS}"
         ## DO NOT ADD GTK keys to c++, that code does not use it
@@ -1783,10 +1783,10 @@ if test "$pkgfound" = "yes"; then
         LIBS="${LINKERFLAGS} ${LIBS} ${LFLAGS}"
         LFLAGS="${LIBS}"
     else
-        echo 'GTK+2.0' not found: compiling without GTK+
+        echo "* GTK+2.0 not found: compiling without GTK+ support"
     fi
 else
-    echo 'Package config' not found: compiling without GTK+
+    echo "* pkg-config/pkgconfig not found: compiling without GTK+ support"
 fi
 
 if test -z "${R_HOME}"; then
